### ISSUE TITLE
Copyedit

### ISSUE THREAD

**Issue by MarcScott** [raspberrypilearning/microbit-game-controller#1]
Hi @LornaLynch or @lauraclay 
Could I get **another** copy edit please. Sorry to be swamping you of late.
Cheers

**Comment by LornaLynch** [comment]
I can take this: just give me a moment to get settled.

**Comment by LornaLynch** [comment]
Actually, strike that: I have something urgent. Can grab it later if you haven't already @lauraclay

**Comment by lauraclay** [comment]
Just seen this - will get on it now.

**Comment by lauraclay** [comment]
Lorna and I have been assigned an urgent (large) editing job, but we'll get back on this ASAP...

**Comment by MarcScott** [comment]
That's fine. Thanks

**Comment by LornaLynch** [comment]
The resource website URL needs to be added when it becomes available.

**Comment by LornaLynch** [comment]
Is the link in software.md correct? It looks odd to me, but I'm no expert.

**Comment by LornaLynch** [comment]
@MarcScott Copy editing finished barring the two minor issues/checks above. Also the sprite images in the worksheet look pretty massive: is this ok? 

If these things are fine, we can close this issue out.

**Comment by MarcScott** [comment]
Thank you
